### ISSUE TITLE
MD previewer

### ISSUE THREAD

**Issue by ErykKul** [gdcc/dataverse-previewers#22]
We can synchronize GitHub and GitLab repositories into Dataverse. However, these repositories have most often the README file in ``.md`` format, not ``.txt``. The general idea is then to add a previewer for ``.md`` files. I will try to work out a pull request for the previewer.

As a start point, I am going to look at the [https://showdownjs.com/](https://showdownjs.com/) 
[showdownjs/showdown](https://github.com/showdownjs/showdown)

**Comment by qqmyers** [comment]
is this closed by #26?

**Comment by ErykKul** [comment]
Yes.
