### ISSUE TITLE
docs: add recommended ExposeHeaders to CORS example

### ISSUE THREAD

**Issue by donsizemore** [gdcc/dataverse-previewers#28]
The text mentions additional options not reflected in the CORS examples:

`"ExposeHeaders": ["ETag", "Content-Encoding", "Content-Range", "Accept-Ranges"]`

**Comment by donsizemore** [comment]
@qqmyers I edited the wiki directly; please check behind me?

**Comment by qqmyers** [comment]
done - thanks!
