### ISSUE TITLE
curl returns no data

### ISSUE THREAD

**Issue by DonRichards** [gdcc/dataverse-previewers#34]
How do I get it to list?

This is what I get in return.
```shell
curl http://localhost:8080/api/admin/externalTools

{"status":"OK","data":[]}
```

Do I need to run this command from a specific directory?
How do I know if the curl was fine (authenticated correctly)?

**Comment by shlake** [comment]
@DonRichards here are the actual `curl` commands for the various previewers.
https://github.com/gdcc/dataverse-previewers/blob/master/5.2curlcommands.md

**Comment by DonRichards** [comment]
Thanks, that helped
