### ISSUE TITLE
HtmlPreview issue with <style> tag

### ISSUE THREAD

**Issue by luddaniel** [gdcc/dataverse-previewers#49]
It seems like HtmlPreview has issue with `<style>` tag. No analysis as been done.
All CSS content is shown as text :
![Capture du 2023-12-22 14-54-37](https://github.com/gdcc/dataverse-previewers/assets/83018819/56682d4f-111c-43ab-865f-d08bde2254cb)

Here is the html file : [00-Supplementary_files_S00_Read_me_file.zip](https://github.com/gdcc/dataverse-previewers/files/13752986/00-Supplementary_files_S00_Read_me_file.zip)

Tested on all versions from `v1.1.1` to `v1.4`

**Comment by qqmyers** [comment]
Closing assuming the RichHtml previewer solved the problem.
