### ISSUE TITLE
Markdown Previewer Retaining Backslashes in Front of Quotes

### ISSUE THREAD

**Issue by bgunia** [gdcc/dataverse-previewers#94]
We’ve recently started using markdown for our required READMEs. I just noticed that the backslash that we insert before the quotation marks surrounding the dataset title is still visible in the Dataverse markdown previewer (image below). My understanding is that it shouldn’t be visible.  We are on v. 6.2 build 1603-a218417

![MarkdownPreviewerIssue](https://github.com/user-attachments/assets/843c4b6c-e6e5-4e26-9892-62f4996aeccc)

**Comment by qqmyers** [comment]
Hmm - I don't see " listed as a char that needs to be escaped in https://www.markdownguide.org/basic-syntax/#characters-you-can-escape . If it is something that should be ignored, we'd probably need to request changes in https://github.com/showdownjs/showdown?tab=readme-ov-file, which is the library we use. (Their demo also shows \" if you enter it, but will show a plain " if that's all you enter.)

**Comment by bgunia** [comment]
I think the problem stems from the tools that we are using to create the README in markdown format. We provide the researcher with a README template in Word, then we convert it to markdown using [pandoc ](https://pandoc.org/try/), then verify that it looks as expected using [Markdown Live Preview](https://markdownlivepreview.com/). What is interesting is when I use Markdown Live Preview, it ignores the backslash. When I use the tool you reference above, Showdown, the backslashes display. As the markdown syntax does not list quotations as characters that need to be escaped, clearly, we need to use different tools. 
No action needs to be done with respect to the Dataverse readme previewer and I am closing this ticket.
